<div id="fixstacks_meeting-example" data-bind="scope:'fixstacks-ko-example'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text\x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "fixstacks-ko-example": {
                        "component": "Fixstacks_Meeting/js/rhkojs"
                        }
                    }
                }
            }
    }
    </script>
</div>
