<?php

/**
 * @var \Fixstacks\Meeting\Block\Display $block
 */

echo $block->sayAgenda();
?>



<!--<style>-->
<!--table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}-->
<!--td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }-->
<!--tr:nth-child(even) { background-color: #dddddd; }-->
<!--.entity_id{width:2%} .identifier{width:30%}-->
<!---->
<!--</style>-->
<!---->
<!--<table>-->
<!--  <tr>-->
<!--    <th class="entity_id">Id</th>-->
<!--    <th class="identifier">Name</th>-->
<!--    <th>Content</th>-->
<!--  </tr>-->
<!--    --><?php
//        foreach ($block->getAgendaCollection() as $key=>$agenda){
//            echo '<tr>
//                    <td>'.$agenda->getEntityId().'</td>
//                    <td>'.$agenda->getIndentifier().'</td>
//                  </tr>';
//        }
//    ?>
<!--</table>-->
<!---->
<!--</body>-->
<!--</html>-->
